spring.application.name=rkfbank

spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:5441}/${MYSQL_DATABASE:rkfbank}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USER:rkfbank}
spring.datasource.password=${MYSQL_PASSWORD:rkfbank}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

viacep.base-url=https://viacep.com.br/ws
viacep.timeout-ms=3000
